config/routes.rb
Reportwheel::Application.routes.draw do
  
  resources :reports do
    collection do
      get :export_csv
    end
  end

  resources :users
  
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  root :to => "sessions#new"

  resource :sessions
  
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :place
  has_many :reports

  attr_accessible :name, :password, :place_id, :can_login, :phone_number

  validates :place_id, :presence => true
  validates :name, :presence => true
  validates :name, :uniqueness => true

  def self.authenticate(name, password)
    can_login?.where(:name => name, :password => password).first
  end

  def self.can_login?
    where(:can_login => true)
  end

  def members
    User.where(:place_id => self.place.children.select(:id))
  end

  def provincial?
    self.place && self.place.place_type.code == "PHD"
  end

  def od?
    self.place && self.place.place_type.code == "OD"
  end

  def hc?
    self.place && self.place.place_type.code == "HC"
  end

  def self.find_by_phone_number_of_reporting_wheel phone_number_rw
    sender_phone_number = phone_number_rw.gsub(/(sms:\/\/)/, "")
    User.find_by_phone_number sender_phone_number
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # params :page
  def index
    if current_user.place.nil?
      User.all.paginate(:page => params[:page], :per_page => 20)
    else
      @users = current_user.members.paginate(:page => params[:page], :per_page => 20)
    end
  end

  def new
    @user = User.new
    @places = current_user.place.children
  end

  def create
    @user = User.new params[:user]
    @user.can_login = true if current_user.provincial?
    if @user.save
      redirect_to users_url, notice: 'User was successfully created.'
    else
      render action: "new"
    end
  end

  def edit
    @user = User.find(params[:id])
    @places = current_user.place.children
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to users_url, notice: 'User was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_url, notice: 'User was successfully deleted.'
  end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">

    <%= f.label :name %>:
    <%= f.text_field :name %><br />

    <%= f.label :password %>:
    <%= f.text_field :password %><br />

    <%= f.label :phone_number %>:
    <%= f.text_field :phone_number %><br />

    <%= f.label :place_id %>:
    <%= collection_select(:user, :place_id, @places, :id, :name) %><br />

    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %> <br />

<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<%= will_paginate @users %>

<% if @users.any? %>
  <table class="round full table-grid">
    <thead>
      <tr>
        <th>#</th>
        <th>Name</th>
        <th>Phone</th>
        <th>Location</th>
        <th>Type</th>
        <th>Can login?</th>
        <th></th>
      </tr>
    </thead>
    <% @users.each_with_index do |user, i| %>
      <tr>
        <td><%= i + 1 %></td>
        <td title="<%= user.name %>"><%= user.name %></td>
        <td title="<%= user.phone_number %>"><%= user.phone_number %></td>
        <td title="<%= user.place.name %>"><%= user.place.name %></td>
        <td title="<%= user.place.place_type.code %>"><%= user.place.place_type.code %></td>
        <td title="<%= user.can_login %>"><%= user.can_login %></td>
        <td>
          <%= link_to 'Edit', edit_user_path(user) %> |
          <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </table>
  <br/>

  <%= will_paginate @users %>
<% end %>

<%= link_to "New", new_user_url %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %> <br />

<%= link_to 'Back', users_path %>